language: objective-c
osx_image: xcode9.2
xcode_workspace: Shopify.xcworkspace
xcode_scheme: ShopApp_Shopify

before_install:
  - pod repo update

notifications:
  slack:
    rooms:
      - shopclientapp:EBh1k4fcosP8EYhbD1R0S2qm#ios
  email: false

script:
  - xcodebuild -workspace Shopify.xcworkspace -scheme ShopApp_Shopify -configuration 'Debug' -sdk 'iphonesimulator11.2' -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty -f `xcpretty-travis-formatter`
